<?php

return [
    /**
     * Control if the seeder should create a user per role while seeding the data.
     */
    'create_users' => env('LARATRUST_CREATE_USERS', false),

    /**
     * Control if all the laratrust tables should be truncated before running the seeder.
     */
    'truncate_tables' => env('LARATRUST_TRUNCATE_TABLES', false),

    /**
     * Control if all the laratrust pivot tables should be truncated before running the seeder.
     */
    'truncate_pivot_tables' => env('LARATRUST_TRUNCATE_PIVOT_TABLES', false),

    /**
     * Control if default roles other than Admin should be created after seeding.
     */
    'seed_default_roles' => env('LARATRUST_SEED_DEFAULT_ROLES', false),

    'roles_structure' => [
        'Admin' => [
            'User Management' => [

                'Create' => [
                    'create_user',
                    'create_role',
                ],

                'Read' => [
                    'access_user_management_module',
                    'view_user',
                    'view_role',
                    'view_permission',
                    'view_login_activity',
                    'view_activity_trail',
                    'generate_user_management_reports',
                ],

                'Update' => [
                    'update_user',
                    'update_role',
                    'update_permission',
                    'assign_role',
                    'assign_permission',
                ],

                'Delete' => [
                    'delete_user',
                    'delete_role',
                ],
            ],
            'Human Resource' => [
                'Create' => [
                    'create_grievance_type',
                    'create_grievance',
                ],
                'Read' => [
                    'view_grievance_types',
                    'view_grievances',
                    'view_department_grievances',
                ],
                'Update' => [
                    'update_grievance_type',
                    'update_grievance',
                    'update_department_grievances',
                ],
                'Restore' => [
                    'restore_grievance_type',
                    'restore_grievance',
                    'restore_department_grievances',
                ],
                'Delete' => [
                    'archive_grievance_type',
                    'force_delete_grievance_type',
                    'archive_grievance',
                    'force_delete_grievance',
                ],
            ],
            'Human Resource/Performance' => [
                'Create' => [
                    'create_appraisal',
                    'create_warning',
                    'create_exit_interview',
                    'create_termination',
                    'create_resignation',
                ],
                'Read' => [
                    'view_appraisals',
                    'view_warnings',
                    'view_exit_interviews',
                    'view_terminations',
                    'view_resignations',
                ],
                'Update' => [
                    'update_appraisal',
                    'update_warning',
                    'update_exit_interview',
                    'update_termination',
                    'update_resignation',
                ],
                'Restore' => [
                    'restore_appraisal',
                    'restore_warning',
                    'restore_exit_interview',
                    'restore_termination',
                    'restore_resignation',
                ],
                'Delete' => [
                    'archive_appraisal',
                    'archive_warning',
                    'archive_exit_interview',
                    'archive_termination',
                    'archive_resignation',
                    'force_delete_appraisal',
                    'force_delete_warning',
                    'force_delete_exit_interview',
                    'force_delete_termination',
                    'force_delete_resignation',
                ],
            ],
            'Human Resource/Leave Management' => [
                'Create' => [
                    'create_leave_request',
                    'create_leave_delegation_request',
                ],
                'Read' => [
                    'view_leave_requests',
                    'view_leave_grievances',
                    'view_department_leave_requests',
                ],
                'Update' => [
                    'update_leave_request',
                    'approve_leave_request',
                    'update_leave_grievance_request',
                    'approve_leave_grievance_request',
                    'approve_department_leave_request',
                ],
                'Restore' => [
                    'restore_leave_request',
                ],
                'Delete' => [
                    'archive_leave_request',
                    'decline_leave_request',
                    'force_delete_leave_request',
                    'decline_leave_request',
                    'decline_department_leave_request',
                    'force_delete_leave_request',
                ],
            ],
            'Human Resource/Employee Management' => [
                'Create' => [
                    'register employee',
                ],
                'Read' => [
                    'view_employees',
                ],
                'Update' => [
                    'update_employee',
                    'activate_employee',
                ],
                'Restore' => [
                    'restore_employee',
                ],
                'Delete' => [
                    'archive_employee',
                    'deactivate_employee',
                    'force_delete_employee',
                ],
            ],
            'Human Resource/Settings' => [
                'Create' => [
                    'create_duty_station',
                    'create_department',
                    'create_designation',
                    'create_holiday',
                    'create_office',
                    'create_statutory_charge',
                    'register_currency_&_rate',
                    'create_leave_type',
                ],
                'Read' => [
                    'view_duty_stations',
                    'view_departments',
                    'view_designations',
                    'view_holidays',
                    'view_offices',
                    'view_statutory_charges',
                    'view_currencies_&_rates',
                    'view_leave_types',
                ],
                'Update' => [
                    'update_duty_station',
                    'update_department',
                    'update_designation',
                    'update_holiday',
                    'update_office',
                    'update_statutory_charge',
                    'update_currency_&_rate',
                    'update_leave_type',
                ],
                'Restore' => [
                    'restore_duty_station',
                    'restore_department',
                    'restore_designation',
                    'restore_holiday',
                    'restore_office',
                    'restore_statutory_charge',
                    'restore_currency_&_rate',
                    'restore_leave_type',
                ],
                'Delete' => [
                    'archive_duty_station',
                    'archive_department',
                    'archive_designation',
                    'archive_holiday',
                    'archive_office',
                    'archive_statutory_charge',
                    'archive_currency_&_rate',
                    'archive_leave_type',
                    'force_delete_duty_station',
                    'force_delete_department',
                    'force_delete_designation',
                    'force_delete_holiday',
                    'force_delete_office',
                    'force_delete_statutory_charge',
                    'force_delete_currency_&_rate',
                    'force_delete_leave_type',
                ],
            ],
            'Document Management' => [
                'Create' => [
                    'create_document_category',
                    'create_folder',
                    'create_document',
                    'create_document_request',
                ],

                'Read' => [
                    'access_document_management_module',
                    'access_document_management_settings',
                    'view_document_category',
                    'view_folder',
                    'view_document',
                    'view_document_request',

                ],

                'Update' => [
                    'update_document_category',
                    'update_folder',
                    'update_document',
                    'archive_document',
                    'update_document_request',
                ],

                'Delete' => [
                    'delete_document_category',
                    'delete_folder',
                    'delete_document',
                    'delete_document_request',
                ],
            ],
            'Finance Management' => [
                'Create' => [
                    'create_budget',
                    'create_unit_budget',
                    'create_invoice',
                    'create_unit_invoice',
                    'create_ledger',
                    'create_unit_ledger',
                    'create_transaction',
                    'create_payment_request',
                    'create_salary_request',
                    'create_payroll',
                    'create_transfer',
                    'create_journal_entry',
                    'create_charts_of_account',
                    'create_cash_flows',
                    'create_customers',
                    'create_services',
                    'create_unit_services',
                    'create_service_category',
                ],

                'Read' => [
                    'access_finance_module',
                    'access_finance_management_settings',
                    'access_accounting',
                    'manage_all_units',
                    'manage_projects',
                    'manage_project_approvals',
                    'manage_project_requests',
                    'view_unit_budget',
                    'view_organization_budget',
                    'view_all_invoices',
                    'view_unit_invoices',
                    'view_unit_ledger',
                    'view_all_ledger',
                    'view_project_ledger',
                    'view_unit_transactions',
                    'view_all_transactions',
                    'view_transfer',
                    'view_unit_transfers',
                    'view_journal_entry',
                    'view_charts_of_account',
                    'view_cash_flows',
                    'view_customers',
                    'view_services',
                    'view_unit_services',
                    'view_years',
                    'view_currencies',
                    'view_reports',
                    'view_advanced_reports',
                    'view_main_dashboard',
                    'view_unit_dashboard',
                    'view_payment_requests',
                    'view_unit_request',
                    'view_payroll',
                    'view_unit_payroll',
                ],

                'Update' => [
                    'update_unit_budget',
                    'approve_unit_requests',
                    'approve_unit_budget',
                    'update_unit_budget',
                    'update_unit_invoice',
                    'approve_unit_invoice',
                    'approve_all_invoices',
                    'update_all_invoices',
                    'update_ledger',
                    'update_transaction',
                    'approve_transaction',
                    'update_transfer',
                    'approve_transfer',
                    'update_journal_entry',
                    'update_charts_of_account',
                    'update_cash_flows',
                    'update_customers',
                    'update_services',
                    'update_unit_services',
                    'update_years',
                    'update_currencies',
                    'update_service_category',
                    'update_payment_request',
                    'update_salary_request',
                    'update_payroll',
                ],

                'Delete' => [
                    'delete_service_category',
                    'delete_budget',
                    'delete_unit_budget',
                    'delete_invoice',
                    'delete_unit_invoice',
                    'delete_ledger',
                    'delete_transaction',
                    'delete_transfer',
                    'delete_journal_entry',
                    'delete_charts_of_account',
                    'delete_cash_flows',
                    'delete_customers',
                    'delete_services',
                    'delete_service_categories',
                    'delete_years',
                    'delete_currencies',
                    'delete_payment_request',
                    'delete_salary_request',
                    'delete_payroll',
                ],
            ],

            // INVENTORY
            'Inventory' => [

                'Create' => [
                    'create_stockcard_entry',
                    'make_inventory_request',
                    'add_commodtiy',
                    'add_unit_of_measure',
                    'add_commodtiy_category',
                    'add_rejection_reason',
                ],

                'Read' => [
                    'manage_inventory',
                    'view_inventory_report',
                    'access_stock_management',
                    'access_inventory_module',
                    'access_department_request',
                ],

                'Update' => [
                    'issue_item',
                    'receive_inventory_request',
                    'approve_inventory_request',
                    'decline_inventory_request',
                    'approve_department_inventory_request',
                    'decline_department_inventory_request',
                    'receive_allocated_inventory',
                    'decline_allocated_inventory',
                    'update_commodtiy',
                    'update_unit_of_measure',
                    'update_commodtiy_category',
                    'update_rejection_reason',
                ],
            ],
        ],

    ],

    //Configure Default Roles and Permissions
    'default_roles' => [
        // FINANCE MANAGEMENT
        'Finance Management' => [
            'Fms Finance supervisor' => [
                'access_finance_module',
                'access_finance_management_settings',
                'access_accounting',
                'manage_all_units',
                'manage_projects',
                'manage_project_approvals',
                'manage_project_requests',
                'view_unit_budget',
                'view_organization_budget',
                'view_all_invoices',
                'view_unit_invoices',
                'view_unit_ledger',
                'view_all_ledger',
                'view_project_ledger',
                'view_unit_transactions',
                'view_all_transactions',
                'view_transfer',
                'view_unit_transfers',
                'view_journal_entry',
                'view_charts_of_account',
                'view_cash_flows',
                'view_customers',
                'view_services',
                'view_unit_services',
                'view_years',
                'view_currencies',
                'view_reports',
                'view_advanced_reports',
                'view_main_dashboard',
                'view_unit_dashboard',
                'view_payment_requests',
                'view_unit_request',
                'view_payroll',
                'view_unit_payroll',
                'update_unit_budget',
                'approve_unit_requests',
                'approve_unit_budget',
                'update_unit_budget',
                'update_unit_invoice',
                'approve_unit_invoice',
                'approve_all_invoices',
                'update_all_invoices',
                'update_ledger',
                'update_transaction',
                'approve_transaction',
                'update_transfer',
                'approve_transfer',
                'update_journal_entry',
                'update_charts_of_account',
                'update_cash_flows',
                'update_customers',
                'update_services',
                'update_unit_services',
                'update_years',
                'update_currencies',
                'update_service_category',
                'update_payment_request',
                'update_salary_request',
                'update_payroll',
                'delete_service_category',
                'delete_budget',
                'delete_unit_budget',
                'delete_invoice',
                'delete_unit_invoice',
                'delete_ledger',
                'delete_transaction',
                'delete_transfer',
                'delete_journal_entry',
                'delete_charts_of_account',
                'delete_cash_flows',
                'delete_customers',
                'delete_services',
                'delete_service_categories',
                'delete_years',
                'delete_currencies',
                'delete_payment_request',
                'delete_salary_request',
                'delete_payroll',
            ],

            'Fms Finance Admin' => [
                'access_finance_module',
                'access_finance_management_settings',
                'access_accounting',
                'manage_all_units',
                'manage_projects',
                'view_organization_budget',
                'view_all_invoices',
                'view_unit_invoices',
                'view_unit_ledger',
                'view_all_ledger',
                'view_project_ledger',
                'view_unit_transactions',
                'view_all_transactions',
                'view_transfer',
                'view_unit_transfers',
                'view_journal_entry',
                'view_charts_of_account',
                'view_cash_flows',
                'view_customers',
                'view_services',
                'view_unit_services',
                'view_years',
                'view_currencies',
                'view_reports',
                'view_advanced_reports',
                'view_main_dashboard',
                'view_unit_dashboard',
                'view_payment_requests',
                'view_unit_request',
                'view_payroll',
                'view_unit_payroll',
                'update_unit_budget',
                'update_unit_budget',
                'approve_all_invoices',
                'update_all_invoices',
                'approve_transaction',
                'update_transfer',
                'approve_transfer',
                'update_journal_entry',
                'update_charts_of_account',
                'update_cash_flows',
                'update_customers',
                'update_services',
                'update_unit_services',
                'update_years',
                'update_currencies',
                'update_service_category',
                'update_payment_request',
                'update_salary_request',
                'update_payroll',
                'delete_budget',
                'delete_unit_budget',
                'delete_invoice',
                'delete_ledger',
                'delete_journal_entry',
                'delete_charts_of_account',
                'delete_cash_flows',
                'delete_customers',
                'delete_services',
                'delete_service_categories',
                'delete_years',
                'delete_currencies',
            ],
            'Fms Unit supervisor' => [
                'access_finance_module',
                'view_unit_budget',
                'view_unit_transactions',
                'view_unit_invoices',
                'view_unit_ledger',
                'create_unit_invoice',
                'create_unit_budget',
                'create_unit_ledger',
                'create_transaction',
                'create_payment_request',
                'create_salary_request',
                'create_transfer',
                'create_unit_services',
                'update_document_request',
                'view_unit_transfers',
                'view_unit_dashboard',
                'view_unit_services',
                'view_unit_payroll',
                'view_unit_request',
                'update_unit_services',
                'update_unit_budget',
                'approve_unit_requests',
                'approve_unit_budget',
                'update_unit_budget',
                'update_unit_invoice',
                'approve_unit_invoice',
                'update_payment_request',
                'update_unit_services',
            ],

            'Fms Unit User' => [
                'access_finance_module',
                'view_unit_budget',
                'view_unit_transactions',
                'view_unit_invoices',
                'view_unit_ledger',
                'create_unit_invoice',
                'create_unit_budget',
                'create_unit_ledger',
                'create_transaction',
                'create_payment_request',
                'create_salary_request',
                'create_transfer',
                'create_unit_services',
                'view_unit_transfers',
                'view_unit_dashboard',
                'view_unit_services',
                'view_unit_request',
                'update_unit_services',
                'update_unit_budget',
                'update_unit_invoice',
                'update_payment_request',
                'update_unit_services',
            ],

            'Fms Project User' => [
                'access_finance_module',
                'manage_projects',
                'manage_project_approvals',
            ],

            
            'Fms Authorizer' => [
              'access_finance_module',
              'approve_unit_requests',
              'view_all_ledger',
              'view_organization_budget',
              'view_all_invoices',
              'view_reports'
            ],

            'Fms Project Monitor' => [
                'access_finance_module',
                'manage_projects',
                'view_unit_budget',
                'view_unit_transactions',
                'view_unit_invoices',
                'view_unit_ledger',
                'view_unit_dashboard',
                'view_unit_services',
                'view_unit_payroll',
                'view_unit_request',
            ],
        ],
        // DOCUMENT MANAGEMENT
        'Document Management' => [
            'Document Admin' => [
                'create_document_category',
                'create_folder',
                'create_document',
                'create_document_request',
                'access_document_management_module',
                'access_document_management_settings',
                'view_document_category',
                'view_folder',
                'view_document',
                'view_document_request',
                'update_document_category',
                'update_folder',
                'update_document',
                'archive_document',
                'update_document_request',
                'delete_document_category',
                'delete_folder',
                'delete_document',
                'delete_document_request',
            ],
            'Document User' => [
                'create_document',
                'create_document_request',
                'access_document_management_module',
                'view_folder',
                'view_document',
                'view_document_request',
                'update_document',
                'archive_document',
                'update_document_request',
                'delete_document_request',
            ],
        ],

        // INVENTORY
        'Inventory' => [

            'Stores Admin' => [
                'manage_inventory',
                'create_stockcard_entry',
                'make_inventory_request',
                'add_commodtiy',
                'add_unit_of_measure',
                'add_commodtiy_category',
                'add_rejection_reason',
                'view_inventory_report',
                'access_stock_management',
                'access_department_request',
                'access_inventory_module',
                'issue_item',
                'receive_inventory_request',
                'approve_inventory_request',
                'decline_inventory_request',
                'update_commodtiy',
                'update_unit_of_measure',
                'update_commodtiy_category',
                'update_rejection_reason',

            ],

            'Regular Department User' => [
                'make_inventory_request',
                'access_department_request',
                'access_inventory_module',
                'receive_allocated_inventory',
                'decline_allocated_inventory',
            ],

            'Department Head' => [
                'view_inventory_report',
                'access_inventory_module',
                'access_department_request',
                'approve_department_inventory_request',
                'decline_department_inventory_request',
                'receive_allocated_inventory',
                'decline_allocated_inventory',
            ],

        ],
    ],

];
